export type PuterModelOption = {
  id: string;
  label: string;
  provider: string;
  role: "fast" | "balanced" | "reasoning" | "coding";
};

export const PUTER_MODELS: PuterModelOption[] = [
  { id: "gpt-6-luna", label: "GPT-6 Luna", provider: "OpenAI", role: "fast" },
  { id: "gpt-6-sol", label: "GPT-6 Sol", provider: "OpenAI", role: "balanced" },
  { id: "gpt-6-astra", label: "GPT-6 Astra", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-6-luna-pro", label: "GPT-6 Luna Pro", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-5.6-luna", label: "GPT-5.6 Luna", provider: "OpenAI", role: "fast" },
  { id: "gpt-5.6-luna-pro", label: "GPT-5.6 Luna Pro", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-5.6-terra", label: "GPT-5.6 Terra", provider: "OpenAI", role: "balanced" },
  { id: "gpt-5.6-terra-pro", label: "GPT-5.6 Terra Pro", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-5.6-sol", label: "GPT-5.6 Sol", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-5.6-sol-pro", label: "GPT-5.6 Sol Pro", provider: "OpenAI", role: "reasoning" },
  { id: "gpt-5.3-codex", label: "GPT-5.3 Codex", provider: "OpenAI", role: "coding" },
  { id: "gpt-5.1-codex", label: "GPT-5.1 Codex", provider: "OpenAI", role: "coding" },
  { id: "gpt-5.1-codex-mini", label: "GPT-5.1 Codex Mini", provider: "OpenAI", role: "coding" },
  { id: "gpt-5.1-chat", label: "GPT-5.1 Chat", provider: "OpenAI", role: "balanced" },
  { id: "claude-fable-5", label: "Claude Fable 5", provider: "Anthropic", role: "reasoning" },
  { id: "claude-fable-5-1", label: "Claude Fable 5.1", provider: "Anthropic", role: "reasoning" },
  { id: "claude-opus-5", label: "Claude Opus 5", provider: "Anthropic", role: "reasoning" },
  { id: "claude-opus-5-fast", label: "Claude Opus 5 Fast", provider: "Anthropic", role: "fast" },
  { id: "claude-opus-4-8", label: "Claude Opus 4.8", provider: "Anthropic", role: "reasoning" },
  { id: "claude-opus-4-8-fast", label: "Claude Opus 4.8 Fast", provider: "Anthropic", role: "fast" },
  { id: "claude-opus-4-6", label: "Claude Opus 4.6", provider: "Anthropic", role: "reasoning" },
  { id: "claude-sonnet-5", label: "Claude Sonnet 5", provider: "Anthropic", role: "balanced" },
  { id: "claude-haiku-4-5", label: "Claude Haiku 4.5", provider: "Anthropic", role: "fast" },
  { id: "grok-4-7", label: "Grok 4.7", provider: "xAI", role: "reasoning" },
  { id: "grok-4.5", label: "Grok 4.5", provider: "xAI", role: "balanced" },
  { id: "glm-5.3-flash", label: "GLM 5.3 Flash", provider: "Z.AI", role: "fast" },
  { id: "glm-5.3-prime", label: "GLM 5.3 Prime", provider: "Z.AI", role: "reasoning" },
  { id: "glm-5.2-fast", label: "GLM 5.2 Fast", provider: "Z.AI", role: "fast" },
  { id: "glm-5.2", label: "GLM 5.2", provider: "Z.AI", role: "balanced" },
  { id: "glm-5", label: "GLM 5", provider: "Z.AI", role: "reasoning" },
  { id: "qwen3.8-max", label: "Qwen3.8 Max", provider: "Qwen", role: "reasoning" },
  { id: "qwen3-max-thinking", label: "Qwen3 Max Thinking", provider: "Qwen", role: "reasoning" },
  { id: "qwen3.7-max", label: "Qwen3.7 Max", provider: "Qwen", role: "reasoning" },
  { id: "qwen3.7-plus", label: "Qwen3.7 Plus", provider: "Qwen", role: "balanced" },
  { id: "qwen3-coder-next", label: "Qwen3 Coder Next", provider: "Qwen", role: "coding" },
  { id: "kimi-k2.7-code", label: "Kimi K2.7 Code", provider: "Moonshot AI", role: "coding" },
  { id: "kimi-k2.7-code-highspeed", label: "Kimi K2.7 Code Highspeed", provider: "Moonshot AI", role: "fast" },
  { id: "minimax-m3", label: "MiniMax M3", provider: "MiniMax", role: "balanced" },
  { id: "minimax-m2.5", label: "MiniMax M2.5", provider: "MiniMax", role: "balanced" },
  { id: "step-3.7-flash", label: "Step 3.7 Flash", provider: "StepFun", role: "fast" },
  { id: "deepseek/deepseek-v4.1-flash:free", label: "DeepSeek V4.1 Flash • FREE", provider: "DeepSeek", role: "fast" },
  { id: "deepseek/deepseek-v4-flash-0731", label: "DeepSeek V4 Flash (0731)", provider: "DeepSeek", role: "fast" },
  { id: "deepseek/deepseek-v4-flash", label: "DeepSeek V4 Flash", provider: "DeepSeek", role: "fast" },
  { id: "deepseek/deepseek-v4-pro-0813", label: "DeepSeek V4 Pro (0813)", provider: "DeepSeek", role: "reasoning" },
  { id: "deepseek/deepseek-v4-pro", label: "DeepSeek V4 Pro", provider: "DeepSeek", role: "reasoning" },
  { id: "deepseek/deepseek-v3.2", label: "DeepSeek V3.2", provider: "DeepSeek", role: "reasoning" },
  { id: "qwen/qwen3.8-27b-abliterated-cyber:free", label: "Qwen3.8 27B Abliterated Cyber • FREE", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.8-max", label: "Qwen3.8 Max", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.8-27b", label: "Qwen3.8 27B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.8-flash", label: "Qwen3.8 Flash", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3.6-flash", label: "Qwen3.6 Flash", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3.5-flash", label: "Qwen3.5 Flash", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3.7-max", label: "Qwen3.7 Max", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-coder-next", label: "Qwen3 Coder Next", provider: "Qwen", role: "coding" },
  { id: "qwen/qwen3-vl-flash", label: "Qwen3-VL Flash", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3.8-2.4t-a95b", label: "Qwen3.8 2.4T A95B", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.7-max-2026-06-08", label: "Qwen3.7 Max (2026-06-08)", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.7-max-2026-05-20", label: "Qwen3.7 Max (2026-05-20)", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.6-27b", label: "Qwen3.6 27B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-122b-a10b", label: "Qwen3.5 122B A10B", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.5-27b", label: "Qwen3.5 27B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-35b-a3b", label: "Qwen3.5 35B A3B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-397b-a17b", label: "Qwen3.5 397B A17B", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3.5-plus", label: "Qwen3.5 Plus", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-plus-2026-02-15", label: "Qwen3.5 Plus (2026-02-15)", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-plus-2026-04-20", label: "Qwen3.5 Plus (2026-04-20)", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3.5-omni-flash", label: "Qwen3.5-Omni Flash", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3.5-omni-plus", label: "Qwen3.5-Omni Plus", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-max", label: "Qwen3 Max", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-max-2026-01-23", label: "Qwen3 Max (2026-01-23)", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-235b-a22b", label: "Qwen3 235B A22B", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-235b-a22b-thinking-2507", label: "Qwen3 235B A22B Thinking 2507", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-235b-a22b-instruct-2507", label: "Qwen3 235B A22B Instruct 2507", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-30b-a3b-instruct-2507", label: "Qwen3 30B A3B Instruct 2507", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-30b-a3b-thinking-2507", label: "Qwen3 30B A3B Thinking 2507", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-32b", label: "Qwen3 32B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-14b", label: "Qwen3 14B", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-8b", label: "Qwen3 8B", provider: "Qwen", role: "fast" },
  { id: "qwen/qwen3-coder-480b-a35b-instruct", label: "Qwen3 Coder 480B A35B", provider: "Qwen", role: "coding" },
  { id: "qwen/qwen3-coder-30b-a3b-instruct", label: "Qwen3 Coder 30B A3B Instruct", provider: "Qwen", role: "coding" },
  { id: "qwen/qwen3-vl-8b-thinking", label: "Qwen3 VL 8B Thinking", provider: "Qwen", role: "reasoning" },
  { id: "qwen/qwen3-vl-30b-a3b-instruct", label: "Qwen3 VL 30B A3B Instruct", provider: "Qwen", role: "balanced" },
  { id: "qwen/qwen3-vl-30b-a3b-thinking", label: "Qwen3 VL 30B A3B Thinking", provider: "Qwen", role: "reasoning" },
  { id: "deepseek/deepseek-v3.1", label: "DeepSeek V3.1", provider: "DeepSeek", role: "reasoning" },
  { id: "deepseek/deepseek-v3.1-terminus", label: "DeepSeek V3.1 Terminus", provider: "DeepSeek", role: "reasoning" },
  { id: "deepseek/deepseek-v3.2-exp", label: "DeepSeek V3.2 Exp", provider: "DeepSeek", role: "reasoning" },
  { id: "byteplus/seed-2-1-turbo", label: "Seed 2.1 Turbo", provider: "ByteDance Seed", role: "fast" },
  { id: "byteplus/seed-2-0-mini-260428", label: "Seed 2.0 Mini 260428", provider: "BytePlus", role: "fast" },
  { id: "byteplus/seed-2-0-lite-260428", label: "Seed 2.0 Lite 260428", provider: "BytePlus", role: "balanced" },
];

export const DEFAULT_PUTER_MODEL = "gpt-5.6-luna";

export function getPuterModel(id: string | undefined) {
  return PUTER_MODELS.find((model) => model.id === id) ?? PUTER_MODELS[0];
}
